<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Classes\Entidades\NovaPasta\**" />
    <EmbeddedResource Remove="Classes\Entidades\NovaPasta\**" />
    <None Remove="Classes\Entidades\NovaPasta\**" />
  </ItemGroup>

</Project>
